/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginTesterRouteImport } from './routes/loginTester'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CallRouteImport } from './routes/call'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesheetIndexRouteImport } from './routes/timesheet/index'
import { Route as StreamIndexRouteImport } from './routes/stream/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TimesheetAdminRouteImport } from './routes/timesheet/admin'
import { Route as StreamVoiceRouteImport } from './routes/stream/voice'
import { Route as StreamReplayRouteImport } from './routes/stream/replay'
import { Route as StreamLiveRouteImport } from './routes/stream/live'
import { Route as StoreWishlistRouteImport } from './routes/store/wishlist'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as RouletteMemberCodeRouteImport } from './routes/roulette/$memberCode'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentFailRouteImport } from './routes/payment/fail'
import { Route as PartnersPartnerIdRouteImport } from './routes/partners/$partnerId'
import { Route as PartnersMemberCodeRouteImport } from './routes/partners/$memberCode'
import { Route as PartnerDashboardRouteImport } from './routes/partner/dashboard'
import { Route as PartnerApplyRouteImport } from './routes/partner/apply'
import { Route as MypageVersionRouteImport } from './routes/mypage/version'
import { Route as MypageTierRouteImport } from './routes/mypage/tier'
import { Route as MypageSubscriptionsRouteImport } from './routes/mypage/subscriptions'
import { Route as MypageSettingsRouteImport } from './routes/mypage/settings'
import { Route as MypagePurchasesRouteImport } from './routes/mypage/purchases'
import { Route as MypageFollowingRouteImport } from './routes/mypage/following'
import { Route as FeedSubscribeRouteImport } from './routes/feed/subscribe'
import { Route as FeedCreateRouteImport } from './routes/feed/create'
import { Route as FeedAllRouteImport } from './routes/feed/all'
import { Route as FeedPostIdRouteImport } from './routes/feed/$postId'
import { Route as DevRouletteRouteImport } from './routes/dev/roulette'
import { Route as DashboardPartnerRouteImport } from './routes/dashboard/partner'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ChatNewRouteImport } from './routes/chat/new'
import { Route as TimesheetAdminIndexRouteImport } from './routes/timesheet/admin/index'
import { Route as StoreRefundsIndexRouteImport } from './routes/store/refunds/index'
import { Route as StoreOrdersIndexRouteImport } from './routes/store/orders/index'
import { Route as MypageSavedIndexRouteImport } from './routes/mypage/saved/index'
import { Route as TimesheetAdminStoresRouteImport } from './routes/timesheet/admin/stores'
import { Route as TimesheetAdminStatsRouteImport } from './routes/timesheet/admin/stats'
import { Route as TimesheetAdminSettingsRouteImport } from './routes/timesheet/admin/settings'
import { Route as TimesheetAdminPartnersRouteImport } from './routes/timesheet/admin/partners'
import { Route as TimesheetAdminManagersRouteImport } from './routes/timesheet/admin/managers'
import { Route as TimesheetAdminAuditRouteImport } from './routes/timesheet/admin/audit'
import { Route as StreamVideoRoomIdRouteImport } from './routes/stream/video/$roomId'
import { Route as StreamChatRoomIdRouteImport } from './routes/stream/chat/$roomId'
import { Route as StoreRefundsRefundIdRouteImport } from './routes/store/refunds/$refundId'
import { Route as StoreProductsProductIdRouteImport } from './routes/store/products/$productId'
import { Route as StorePaymentSuccessRouteImport } from './routes/store/payment/success'
import { Route as StorePaymentFailRouteImport } from './routes/store/payment/fail'
import { Route as StorePartnerProductsRouteImport } from './routes/store/partner/products'
import { Route as StorePartnerOrdersRouteImport } from './routes/store/partner/orders'
import { Route as StorePartnerInsightsRouteImport } from './routes/store/partner/insights'
import { Route as StorePartnerCollaborationRouteImport } from './routes/store/partner/collaboration'
import { Route as StorePartnerAgreementRouteImport } from './routes/store/partner/agreement'
import { Route as StoreOrdersOrderIdRouteImport } from './routes/store/orders/$orderId'
import { Route as StoreDigitalDownloadsRouteImport } from './routes/store/digital/downloads'
import { Route as StoreAdminShipmentRequestsRouteImport } from './routes/store/admin/shipment-requests'
import { Route as StoreAdminInsightsRouteImport } from './routes/store/admin/insights'
import { Route as StoreAdminCollaborationRouteImport } from './routes/store/admin/collaboration'
import { Route as MypageSavedAlbumIdRouteImport } from './routes/mypage/saved/$albumId'
import { Route as MypagePurchasesOrderIdRouteImport } from './routes/mypage/purchases/$orderId'
import { Route as MypageInventoryRouletteRouteImport } from './routes/mypage/inventory/roulette'
import { Route as MypageInventoryDigitalCollectionRouteImport } from './routes/mypage/inventory/digital-collection'
import { Route as DashboardPartnerRouletteRequestsRouteImport } from './routes/dashboard/partner/roulette-requests'
import { Route as DashboardPartnerRouletteRouteImport } from './routes/dashboard/partner/roulette'
import { Route as StreamVideoWebrtcBroadcastRoomIdRouteImport } from './routes/stream/video/webrtc-broadcast.$roomId'
import { Route as StreamVideoRehearsalRoomIdRouteImport } from './routes/stream/video/rehearsal.$roomId'
import { Route as StreamVideoHlsRehearsalRoomIdRouteImport } from './routes/stream/video/hls-rehearsal.$roomId'
import { Route as StorePartnerProductsNewRouteImport } from './routes/store/partner/products/new'
import { Route as StoreOrdersOrderIdViewerRouteImport } from './routes/store/orders/$orderId/viewer'
import { Route as StoreDigitalOrdersOrderIdRouteImport } from './routes/store/digital/orders/$orderId'
import { Route as DashboardPartnerInventoryRouletteRouteImport } from './routes/dashboard/partner/inventory/roulette'
import { Route as StorePartnerProductsNewUploadRouteImport } from './routes/store/partner/products/new/upload'
import { Route as StorePartnerProductsProductIdUploadRouteImport } from './routes/store/partner/products/$productId/upload'
import { Route as StorePartnerProductsProductIdPreviewRouteImport } from './routes/store/partner/products/$productId/preview'
import { Route as StorePartnerProductsProductIdEditRouteImport } from './routes/store/partner/products/$productId/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTesterRoute = LoginTesterRouteImport.update({
  id: '/loginTester',
  path: '/loginTester',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetIndexRoute = TimesheetIndexRouteImport.update({
  id: '/timesheet/',
  path: '/timesheet/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamIndexRoute = StreamIndexRouteImport.update({
  id: '/stream/',
  path: '/stream/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetAdminRoute = TimesheetAdminRouteImport.update({
  id: '/timesheet/admin',
  path: '/timesheet/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamVoiceRoute = StreamVoiceRouteImport.update({
  id: '/stream/voice',
  path: '/stream/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamReplayRoute = StreamReplayRouteImport.update({
  id: '/stream/replay',
  path: '/stream/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamLiveRoute = StreamLiveRouteImport.update({
  id: '/stream/live',
  path: '/stream/live',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreWishlistRoute = StoreWishlistRouteImport.update({
  id: '/store/wishlist',
  path: '/store/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/store/cart',
  path: '/store/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteMemberCodeRoute = RouletteMemberCodeRouteImport.update({
  id: '/roulette/$memberCode',
  path: '/roulette/$memberCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailRoute = PaymentFailRouteImport.update({
  id: '/payment/fail',
  path: '/payment/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPartnerIdRoute = PartnersPartnerIdRouteImport.update({
  id: '/partners/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersMemberCodeRoute = PartnersMemberCodeRouteImport.update({
  id: '/partners/$memberCode',
  path: '/partners/$memberCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerApplyRoute = PartnerApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PartnerRoute,
} as any)
const MypageVersionRoute = MypageVersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => MypageRoute,
} as any)
const MypageTierRoute = MypageTierRouteImport.update({
  id: '/tier',
  path: '/tier',
  getParentRoute: () => MypageRoute,
} as any)
const MypageSubscriptionsRoute = MypageSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MypageRoute,
} as any)
const MypageSettingsRoute = MypageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MypageRoute,
} as any)
const MypagePurchasesRoute = MypagePurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => MypageRoute,
} as any)
const MypageFollowingRoute = MypageFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MypageRoute,
} as any)
const FeedSubscribeRoute = FeedSubscribeRouteImport.update({
  id: '/feed/subscribe',
  path: '/feed/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedCreateRoute = FeedCreateRouteImport.update({
  id: '/feed/create',
  path: '/feed/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedAllRoute = FeedAllRouteImport.update({
  id: '/feed/all',
  path: '/feed/all',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPostIdRoute = FeedPostIdRouteImport.update({
  id: '/feed/$postId',
  path: '/feed/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouletteRoute = DevRouletteRouteImport.update({
  id: '/dev/roulette',
  path: '/dev/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPartnerRoute = DashboardPartnerRouteImport.update({
  id: '/dashboard/partner',
  path: '/dashboard/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatRoute,
} as any)
const TimesheetAdminIndexRoute = TimesheetAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const StoreRefundsIndexRoute = StoreRefundsIndexRouteImport.update({
  id: '/store/refunds/',
  path: '/store/refunds/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOrdersIndexRoute = StoreOrdersIndexRouteImport.update({
  id: '/store/orders/',
  path: '/store/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageSavedIndexRoute = MypageSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => MypageRoute,
} as any)
const TimesheetAdminStoresRoute = TimesheetAdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const TimesheetAdminStatsRoute = TimesheetAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const TimesheetAdminSettingsRoute = TimesheetAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const TimesheetAdminPartnersRoute = TimesheetAdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const TimesheetAdminManagersRoute = TimesheetAdminManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const TimesheetAdminAuditRoute = TimesheetAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => TimesheetAdminRoute,
} as any)
const StreamVideoRoomIdRoute = StreamVideoRoomIdRouteImport.update({
  id: '/stream/video/$roomId',
  path: '/stream/video/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamChatRoomIdRoute = StreamChatRoomIdRouteImport.update({
  id: '/stream/chat/$roomId',
  path: '/stream/chat/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRefundsRefundIdRoute = StoreRefundsRefundIdRouteImport.update({
  id: '/store/refunds/$refundId',
  path: '/store/refunds/$refundId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductsProductIdRoute = StoreProductsProductIdRouteImport.update({
  id: '/store/products/$productId',
  path: '/store/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const StorePaymentSuccessRoute = StorePaymentSuccessRouteImport.update({
  id: '/store/payment/success',
  path: '/store/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StorePaymentFailRoute = StorePaymentFailRouteImport.update({
  id: '/store/payment/fail',
  path: '/store/payment/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const StorePartnerProductsRoute = StorePartnerProductsRouteImport.update({
  id: '/store/partner/products',
  path: '/store/partner/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StorePartnerOrdersRoute = StorePartnerOrdersRouteImport.update({
  id: '/store/partner/orders',
  path: '/store/partner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StorePartnerInsightsRoute = StorePartnerInsightsRouteImport.update({
  id: '/store/partner/insights',
  path: '/store/partner/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StorePartnerCollaborationRoute =
  StorePartnerCollaborationRouteImport.update({
    id: '/store/partner/collaboration',
    path: '/store/partner/collaboration',
    getParentRoute: () => rootRouteImport,
  } as any)
const StorePartnerAgreementRoute = StorePartnerAgreementRouteImport.update({
  id: '/store/partner/agreement',
  path: '/store/partner/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOrdersOrderIdRoute = StoreOrdersOrderIdRouteImport.update({
  id: '/store/orders/$orderId',
  path: '/store/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreDigitalDownloadsRoute = StoreDigitalDownloadsRouteImport.update({
  id: '/store/digital/downloads',
  path: '/store/digital/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminShipmentRequestsRoute =
  StoreAdminShipmentRequestsRouteImport.update({
    id: '/store/admin/shipment-requests',
    path: '/store/admin/shipment-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoreAdminInsightsRoute = StoreAdminInsightsRouteImport.update({
  id: '/store/admin/insights',
  path: '/store/admin/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminCollaborationRoute = StoreAdminCollaborationRouteImport.update({
  id: '/store/admin/collaboration',
  path: '/store/admin/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageSavedAlbumIdRoute = MypageSavedAlbumIdRouteImport.update({
  id: '/saved/$albumId',
  path: '/saved/$albumId',
  getParentRoute: () => MypageRoute,
} as any)
const MypagePurchasesOrderIdRoute = MypagePurchasesOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => MypagePurchasesRoute,
} as any)
const MypageInventoryRouletteRoute = MypageInventoryRouletteRouteImport.update({
  id: '/inventory/roulette',
  path: '/inventory/roulette',
  getParentRoute: () => MypageRoute,
} as any)
const MypageInventoryDigitalCollectionRoute =
  MypageInventoryDigitalCollectionRouteImport.update({
    id: '/inventory/digital-collection',
    path: '/inventory/digital-collection',
    getParentRoute: () => MypageRoute,
  } as any)
const DashboardPartnerRouletteRequestsRoute =
  DashboardPartnerRouletteRequestsRouteImport.update({
    id: '/roulette-requests',
    path: '/roulette-requests',
    getParentRoute: () => DashboardPartnerRoute,
  } as any)
const DashboardPartnerRouletteRoute =
  DashboardPartnerRouletteRouteImport.update({
    id: '/roulette',
    path: '/roulette',
    getParentRoute: () => DashboardPartnerRoute,
  } as any)
const StreamVideoWebrtcBroadcastRoomIdRoute =
  StreamVideoWebrtcBroadcastRoomIdRouteImport.update({
    id: '/stream/video/webrtc-broadcast/$roomId',
    path: '/stream/video/webrtc-broadcast/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StreamVideoRehearsalRoomIdRoute =
  StreamVideoRehearsalRoomIdRouteImport.update({
    id: '/stream/video/rehearsal/$roomId',
    path: '/stream/video/rehearsal/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StreamVideoHlsRehearsalRoomIdRoute =
  StreamVideoHlsRehearsalRoomIdRouteImport.update({
    id: '/stream/video/hls-rehearsal/$roomId',
    path: '/stream/video/hls-rehearsal/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StorePartnerProductsNewRoute = StorePartnerProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StorePartnerProductsRoute,
} as any)
const StoreOrdersOrderIdViewerRoute =
  StoreOrdersOrderIdViewerRouteImport.update({
    id: '/viewer',
    path: '/viewer',
    getParentRoute: () => StoreOrdersOrderIdRoute,
  } as any)
const StoreDigitalOrdersOrderIdRoute =
  StoreDigitalOrdersOrderIdRouteImport.update({
    id: '/store/digital/orders/$orderId',
    path: '/store/digital/orders/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPartnerInventoryRouletteRoute =
  DashboardPartnerInventoryRouletteRouteImport.update({
    id: '/inventory/roulette',
    path: '/inventory/roulette',
    getParentRoute: () => DashboardPartnerRoute,
  } as any)
const StorePartnerProductsNewUploadRoute =
  StorePartnerProductsNewUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => StorePartnerProductsNewRoute,
  } as any)
const StorePartnerProductsProductIdUploadRoute =
  StorePartnerProductsProductIdUploadRouteImport.update({
    id: '/$productId/upload',
    path: '/$productId/upload',
    getParentRoute: () => StorePartnerProductsRoute,
  } as any)
const StorePartnerProductsProductIdPreviewRoute =
  StorePartnerProductsProductIdPreviewRouteImport.update({
    id: '/$productId/preview',
    path: '/$productId/preview',
    getParentRoute: () => StorePartnerProductsRoute,
  } as any)
const StorePartnerProductsProductIdEditRoute =
  StorePartnerProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => StorePartnerProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/chat': typeof ChatRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/loginTester': typeof LoginTesterRoute
  '/membership': typeof MembershipRoute
  '/messages': typeof MessagesRoute
  '/mypage': typeof MypageRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/chat/new': typeof ChatNewRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/partner': typeof DashboardPartnerRouteWithChildren
  '/dev/roulette': typeof DevRouletteRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/feed/all': typeof FeedAllRoute
  '/feed/create': typeof FeedCreateRoute
  '/feed/subscribe': typeof FeedSubscribeRoute
  '/mypage/following': typeof MypageFollowingRoute
  '/mypage/purchases': typeof MypagePurchasesRouteWithChildren
  '/mypage/settings': typeof MypageSettingsRoute
  '/mypage/subscriptions': typeof MypageSubscriptionsRoute
  '/mypage/tier': typeof MypageTierRoute
  '/mypage/version': typeof MypageVersionRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partners/$memberCode': typeof PartnersMemberCodeRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/roulette/$memberCode': typeof RouletteMemberCodeRoute
  '/store/cart': typeof StoreCartRoute
  '/store/wishlist': typeof StoreWishlistRoute
  '/stream/live': typeof StreamLiveRoute
  '/stream/replay': typeof StreamReplayRoute
  '/stream/voice': typeof StreamVoiceRoute
  '/timesheet/admin': typeof TimesheetAdminRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/stream': typeof StreamIndexRoute
  '/timesheet': typeof TimesheetIndexRoute
  '/dashboard/partner/roulette': typeof DashboardPartnerRouletteRoute
  '/dashboard/partner/roulette-requests': typeof DashboardPartnerRouletteRequestsRoute
  '/mypage/inventory/digital-collection': typeof MypageInventoryDigitalCollectionRoute
  '/mypage/inventory/roulette': typeof MypageInventoryRouletteRoute
  '/mypage/purchases/$orderId': typeof MypagePurchasesOrderIdRoute
  '/mypage/saved/$albumId': typeof MypageSavedAlbumIdRoute
  '/store/admin/collaboration': typeof StoreAdminCollaborationRoute
  '/store/admin/insights': typeof StoreAdminInsightsRoute
  '/store/admin/shipment-requests': typeof StoreAdminShipmentRequestsRoute
  '/store/digital/downloads': typeof StoreDigitalDownloadsRoute
  '/store/orders/$orderId': typeof StoreOrdersOrderIdRouteWithChildren
  '/store/partner/agreement': typeof StorePartnerAgreementRoute
  '/store/partner/collaboration': typeof StorePartnerCollaborationRoute
  '/store/partner/insights': typeof StorePartnerInsightsRoute
  '/store/partner/orders': typeof StorePartnerOrdersRoute
  '/store/partner/products': typeof StorePartnerProductsRouteWithChildren
  '/store/payment/fail': typeof StorePaymentFailRoute
  '/store/payment/success': typeof StorePaymentSuccessRoute
  '/store/products/$productId': typeof StoreProductsProductIdRoute
  '/store/refunds/$refundId': typeof StoreRefundsRefundIdRoute
  '/stream/chat/$roomId': typeof StreamChatRoomIdRoute
  '/stream/video/$roomId': typeof StreamVideoRoomIdRoute
  '/timesheet/admin/audit': typeof TimesheetAdminAuditRoute
  '/timesheet/admin/managers': typeof TimesheetAdminManagersRoute
  '/timesheet/admin/partners': typeof TimesheetAdminPartnersRoute
  '/timesheet/admin/settings': typeof TimesheetAdminSettingsRoute
  '/timesheet/admin/stats': typeof TimesheetAdminStatsRoute
  '/timesheet/admin/stores': typeof TimesheetAdminStoresRoute
  '/mypage/saved': typeof MypageSavedIndexRoute
  '/store/orders': typeof StoreOrdersIndexRoute
  '/store/refunds': typeof StoreRefundsIndexRoute
  '/timesheet/admin/': typeof TimesheetAdminIndexRoute
  '/dashboard/partner/inventory/roulette': typeof DashboardPartnerInventoryRouletteRoute
  '/store/digital/orders/$orderId': typeof StoreDigitalOrdersOrderIdRoute
  '/store/orders/$orderId/viewer': typeof StoreOrdersOrderIdViewerRoute
  '/store/partner/products/new': typeof StorePartnerProductsNewRouteWithChildren
  '/stream/video/hls-rehearsal/$roomId': typeof StreamVideoHlsRehearsalRoomIdRoute
  '/stream/video/rehearsal/$roomId': typeof StreamVideoRehearsalRoomIdRoute
  '/stream/video/webrtc-broadcast/$roomId': typeof StreamVideoWebrtcBroadcastRoomIdRoute
  '/store/partner/products/$productId/edit': typeof StorePartnerProductsProductIdEditRoute
  '/store/partner/products/$productId/preview': typeof StorePartnerProductsProductIdPreviewRoute
  '/store/partner/products/$productId/upload': typeof StorePartnerProductsProductIdUploadRoute
  '/store/partner/products/new/upload': typeof StorePartnerProductsNewUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/chat': typeof ChatRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/loginTester': typeof LoginTesterRoute
  '/membership': typeof MembershipRoute
  '/messages': typeof MessagesRoute
  '/mypage': typeof MypageRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/chat/new': typeof ChatNewRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/partner': typeof DashboardPartnerRouteWithChildren
  '/dev/roulette': typeof DevRouletteRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/feed/all': typeof FeedAllRoute
  '/feed/create': typeof FeedCreateRoute
  '/feed/subscribe': typeof FeedSubscribeRoute
  '/mypage/following': typeof MypageFollowingRoute
  '/mypage/purchases': typeof MypagePurchasesRouteWithChildren
  '/mypage/settings': typeof MypageSettingsRoute
  '/mypage/subscriptions': typeof MypageSubscriptionsRoute
  '/mypage/tier': typeof MypageTierRoute
  '/mypage/version': typeof MypageVersionRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partners/$memberCode': typeof PartnersMemberCodeRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/roulette/$memberCode': typeof RouletteMemberCodeRoute
  '/store/cart': typeof StoreCartRoute
  '/store/wishlist': typeof StoreWishlistRoute
  '/stream/live': typeof StreamLiveRoute
  '/stream/replay': typeof StreamReplayRoute
  '/stream/voice': typeof StreamVoiceRoute
  '/admin': typeof AdminIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/stream': typeof StreamIndexRoute
  '/timesheet': typeof TimesheetIndexRoute
  '/dashboard/partner/roulette': typeof DashboardPartnerRouletteRoute
  '/dashboard/partner/roulette-requests': typeof DashboardPartnerRouletteRequestsRoute
  '/mypage/inventory/digital-collection': typeof MypageInventoryDigitalCollectionRoute
  '/mypage/inventory/roulette': typeof MypageInventoryRouletteRoute
  '/mypage/purchases/$orderId': typeof MypagePurchasesOrderIdRoute
  '/mypage/saved/$albumId': typeof MypageSavedAlbumIdRoute
  '/store/admin/collaboration': typeof StoreAdminCollaborationRoute
  '/store/admin/insights': typeof StoreAdminInsightsRoute
  '/store/admin/shipment-requests': typeof StoreAdminShipmentRequestsRoute
  '/store/digital/downloads': typeof StoreDigitalDownloadsRoute
  '/store/orders/$orderId': typeof StoreOrdersOrderIdRouteWithChildren
  '/store/partner/agreement': typeof StorePartnerAgreementRoute
  '/store/partner/collaboration': typeof StorePartnerCollaborationRoute
  '/store/partner/insights': typeof StorePartnerInsightsRoute
  '/store/partner/orders': typeof StorePartnerOrdersRoute
  '/store/partner/products': typeof StorePartnerProductsRouteWithChildren
  '/store/payment/fail': typeof StorePaymentFailRoute
  '/store/payment/success': typeof StorePaymentSuccessRoute
  '/store/products/$productId': typeof StoreProductsProductIdRoute
  '/store/refunds/$refundId': typeof StoreRefundsRefundIdRoute
  '/stream/chat/$roomId': typeof StreamChatRoomIdRoute
  '/stream/video/$roomId': typeof StreamVideoRoomIdRoute
  '/timesheet/admin/audit': typeof TimesheetAdminAuditRoute
  '/timesheet/admin/managers': typeof TimesheetAdminManagersRoute
  '/timesheet/admin/partners': typeof TimesheetAdminPartnersRoute
  '/timesheet/admin/settings': typeof TimesheetAdminSettingsRoute
  '/timesheet/admin/stats': typeof TimesheetAdminStatsRoute
  '/timesheet/admin/stores': typeof TimesheetAdminStoresRoute
  '/mypage/saved': typeof MypageSavedIndexRoute
  '/store/orders': typeof StoreOrdersIndexRoute
  '/store/refunds': typeof StoreRefundsIndexRoute
  '/timesheet/admin': typeof TimesheetAdminIndexRoute
  '/dashboard/partner/inventory/roulette': typeof DashboardPartnerInventoryRouletteRoute
  '/store/digital/orders/$orderId': typeof StoreDigitalOrdersOrderIdRoute
  '/store/orders/$orderId/viewer': typeof StoreOrdersOrderIdViewerRoute
  '/store/partner/products/new': typeof StorePartnerProductsNewRouteWithChildren
  '/stream/video/hls-rehearsal/$roomId': typeof StreamVideoHlsRehearsalRoomIdRoute
  '/stream/video/rehearsal/$roomId': typeof StreamVideoRehearsalRoomIdRoute
  '/stream/video/webrtc-broadcast/$roomId': typeof StreamVideoWebrtcBroadcastRoomIdRoute
  '/store/partner/products/$productId/edit': typeof StorePartnerProductsProductIdEditRoute
  '/store/partner/products/$productId/preview': typeof StorePartnerProductsProductIdPreviewRoute
  '/store/partner/products/$productId/upload': typeof StorePartnerProductsProductIdUploadRoute
  '/store/partner/products/new/upload': typeof StorePartnerProductsNewUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/chat': typeof ChatRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/loginTester': typeof LoginTesterRoute
  '/membership': typeof MembershipRoute
  '/messages': typeof MessagesRoute
  '/mypage': typeof MypageRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/chat/new': typeof ChatNewRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/partner': typeof DashboardPartnerRouteWithChildren
  '/dev/roulette': typeof DevRouletteRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/feed/all': typeof FeedAllRoute
  '/feed/create': typeof FeedCreateRoute
  '/feed/subscribe': typeof FeedSubscribeRoute
  '/mypage/following': typeof MypageFollowingRoute
  '/mypage/purchases': typeof MypagePurchasesRouteWithChildren
  '/mypage/settings': typeof MypageSettingsRoute
  '/mypage/subscriptions': typeof MypageSubscriptionsRoute
  '/mypage/tier': typeof MypageTierRoute
  '/mypage/version': typeof MypageVersionRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partners/$memberCode': typeof PartnersMemberCodeRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/roulette/$memberCode': typeof RouletteMemberCodeRoute
  '/store/cart': typeof StoreCartRoute
  '/store/wishlist': typeof StoreWishlistRoute
  '/stream/live': typeof StreamLiveRoute
  '/stream/replay': typeof StreamReplayRoute
  '/stream/voice': typeof StreamVoiceRoute
  '/timesheet/admin': typeof TimesheetAdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/stream/': typeof StreamIndexRoute
  '/timesheet/': typeof TimesheetIndexRoute
  '/dashboard/partner/roulette': typeof DashboardPartnerRouletteRoute
  '/dashboard/partner/roulette-requests': typeof DashboardPartnerRouletteRequestsRoute
  '/mypage/inventory/digital-collection': typeof MypageInventoryDigitalCollectionRoute
  '/mypage/inventory/roulette': typeof MypageInventoryRouletteRoute
  '/mypage/purchases/$orderId': typeof MypagePurchasesOrderIdRoute
  '/mypage/saved/$albumId': typeof MypageSavedAlbumIdRoute
  '/store/admin/collaboration': typeof StoreAdminCollaborationRoute
  '/store/admin/insights': typeof StoreAdminInsightsRoute
  '/store/admin/shipment-requests': typeof StoreAdminShipmentRequestsRoute
  '/store/digital/downloads': typeof StoreDigitalDownloadsRoute
  '/store/orders/$orderId': typeof StoreOrdersOrderIdRouteWithChildren
  '/store/partner/agreement': typeof StorePartnerAgreementRoute
  '/store/partner/collaboration': typeof StorePartnerCollaborationRoute
  '/store/partner/insights': typeof StorePartnerInsightsRoute
  '/store/partner/orders': typeof StorePartnerOrdersRoute
  '/store/partner/products': typeof StorePartnerProductsRouteWithChildren
  '/store/payment/fail': typeof StorePaymentFailRoute
  '/store/payment/success': typeof StorePaymentSuccessRoute
  '/store/products/$productId': typeof StoreProductsProductIdRoute
  '/store/refunds/$refundId': typeof StoreRefundsRefundIdRoute
  '/stream/chat/$roomId': typeof StreamChatRoomIdRoute
  '/stream/video/$roomId': typeof StreamVideoRoomIdRoute
  '/timesheet/admin/audit': typeof TimesheetAdminAuditRoute
  '/timesheet/admin/managers': typeof TimesheetAdminManagersRoute
  '/timesheet/admin/partners': typeof TimesheetAdminPartnersRoute
  '/timesheet/admin/settings': typeof TimesheetAdminSettingsRoute
  '/timesheet/admin/stats': typeof TimesheetAdminStatsRoute
  '/timesheet/admin/stores': typeof TimesheetAdminStoresRoute
  '/mypage/saved/': typeof MypageSavedIndexRoute
  '/store/orders/': typeof StoreOrdersIndexRoute
  '/store/refunds/': typeof StoreRefundsIndexRoute
  '/timesheet/admin/': typeof TimesheetAdminIndexRoute
  '/dashboard/partner/inventory/roulette': typeof DashboardPartnerInventoryRouletteRoute
  '/store/digital/orders/$orderId': typeof StoreDigitalOrdersOrderIdRoute
  '/store/orders/$orderId/viewer': typeof StoreOrdersOrderIdViewerRoute
  '/store/partner/products/new': typeof StorePartnerProductsNewRouteWithChildren
  '/stream/video/hls-rehearsal/$roomId': typeof StreamVideoHlsRehearsalRoomIdRoute
  '/stream/video/rehearsal/$roomId': typeof StreamVideoRehearsalRoomIdRoute
  '/stream/video/webrtc-broadcast/$roomId': typeof StreamVideoWebrtcBroadcastRoomIdRoute
  '/store/partner/products/$productId/edit': typeof StorePartnerProductsProductIdEditRoute
  '/store/partner/products/$productId/preview': typeof StorePartnerProductsProductIdPreviewRoute
  '/store/partner/products/$productId/upload': typeof StorePartnerProductsProductIdUploadRoute
  '/store/partner/products/new/upload': typeof StorePartnerProductsNewUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/chat'
    | '/explore'
    | '/login'
    | '/loginTester'
    | '/membership'
    | '/messages'
    | '/mypage'
    | '/notifications'
    | '/partner'
    | '/points'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/chat/new'
    | '/dashboard/admin'
    | '/dashboard/partner'
    | '/dev/roulette'
    | '/feed/$postId'
    | '/feed/all'
    | '/feed/create'
    | '/feed/subscribe'
    | '/mypage/following'
    | '/mypage/purchases'
    | '/mypage/settings'
    | '/mypage/subscriptions'
    | '/mypage/tier'
    | '/mypage/version'
    | '/partner/apply'
    | '/partner/dashboard'
    | '/partners/$memberCode'
    | '/partners/$partnerId'
    | '/payment/fail'
    | '/payment/success'
    | '/roulette/$memberCode'
    | '/store/cart'
    | '/store/wishlist'
    | '/stream/live'
    | '/stream/replay'
    | '/stream/voice'
    | '/timesheet/admin'
    | '/admin'
    | '/partners'
    | '/stream'
    | '/timesheet'
    | '/dashboard/partner/roulette'
    | '/dashboard/partner/roulette-requests'
    | '/mypage/inventory/digital-collection'
    | '/mypage/inventory/roulette'
    | '/mypage/purchases/$orderId'
    | '/mypage/saved/$albumId'
    | '/store/admin/collaboration'
    | '/store/admin/insights'
    | '/store/admin/shipment-requests'
    | '/store/digital/downloads'
    | '/store/orders/$orderId'
    | '/store/partner/agreement'
    | '/store/partner/collaboration'
    | '/store/partner/insights'
    | '/store/partner/orders'
    | '/store/partner/products'
    | '/store/payment/fail'
    | '/store/payment/success'
    | '/store/products/$productId'
    | '/store/refunds/$refundId'
    | '/stream/chat/$roomId'
    | '/stream/video/$roomId'
    | '/timesheet/admin/audit'
    | '/timesheet/admin/managers'
    | '/timesheet/admin/partners'
    | '/timesheet/admin/settings'
    | '/timesheet/admin/stats'
    | '/timesheet/admin/stores'
    | '/mypage/saved'
    | '/store/orders'
    | '/store/refunds'
    | '/timesheet/admin/'
    | '/dashboard/partner/inventory/roulette'
    | '/store/digital/orders/$orderId'
    | '/store/orders/$orderId/viewer'
    | '/store/partner/products/new'
    | '/stream/video/hls-rehearsal/$roomId'
    | '/stream/video/rehearsal/$roomId'
    | '/stream/video/webrtc-broadcast/$roomId'
    | '/store/partner/products/$productId/edit'
    | '/store/partner/products/$productId/preview'
    | '/store/partner/products/$productId/upload'
    | '/store/partner/products/new/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/chat'
    | '/explore'
    | '/login'
    | '/loginTester'
    | '/membership'
    | '/messages'
    | '/mypage'
    | '/notifications'
    | '/partner'
    | '/points'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/chat/new'
    | '/dashboard/admin'
    | '/dashboard/partner'
    | '/dev/roulette'
    | '/feed/$postId'
    | '/feed/all'
    | '/feed/create'
    | '/feed/subscribe'
    | '/mypage/following'
    | '/mypage/purchases'
    | '/mypage/settings'
    | '/mypage/subscriptions'
    | '/mypage/tier'
    | '/mypage/version'
    | '/partner/apply'
    | '/partner/dashboard'
    | '/partners/$memberCode'
    | '/partners/$partnerId'
    | '/payment/fail'
    | '/payment/success'
    | '/roulette/$memberCode'
    | '/store/cart'
    | '/store/wishlist'
    | '/stream/live'
    | '/stream/replay'
    | '/stream/voice'
    | '/admin'
    | '/partners'
    | '/stream'
    | '/timesheet'
    | '/dashboard/partner/roulette'
    | '/dashboard/partner/roulette-requests'
    | '/mypage/inventory/digital-collection'
    | '/mypage/inventory/roulette'
    | '/mypage/purchases/$orderId'
    | '/mypage/saved/$albumId'
    | '/store/admin/collaboration'
    | '/store/admin/insights'
    | '/store/admin/shipment-requests'
    | '/store/digital/downloads'
    | '/store/orders/$orderId'
    | '/store/partner/agreement'
    | '/store/partner/collaboration'
    | '/store/partner/insights'
    | '/store/partner/orders'
    | '/store/partner/products'
    | '/store/payment/fail'
    | '/store/payment/success'
    | '/store/products/$productId'
    | '/store/refunds/$refundId'
    | '/stream/chat/$roomId'
    | '/stream/video/$roomId'
    | '/timesheet/admin/audit'
    | '/timesheet/admin/managers'
    | '/timesheet/admin/partners'
    | '/timesheet/admin/settings'
    | '/timesheet/admin/stats'
    | '/timesheet/admin/stores'
    | '/mypage/saved'
    | '/store/orders'
    | '/store/refunds'
    | '/timesheet/admin'
    | '/dashboard/partner/inventory/roulette'
    | '/store/digital/orders/$orderId'
    | '/store/orders/$orderId/viewer'
    | '/store/partner/products/new'
    | '/stream/video/hls-rehearsal/$roomId'
    | '/stream/video/rehearsal/$roomId'
    | '/stream/video/webrtc-broadcast/$roomId'
    | '/store/partner/products/$productId/edit'
    | '/store/partner/products/$productId/preview'
    | '/store/partner/products/$productId/upload'
    | '/store/partner/products/new/upload'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/chat'
    | '/explore'
    | '/login'
    | '/loginTester'
    | '/membership'
    | '/messages'
    | '/mypage'
    | '/notifications'
    | '/partner'
    | '/points'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/chat/new'
    | '/dashboard/admin'
    | '/dashboard/partner'
    | '/dev/roulette'
    | '/feed/$postId'
    | '/feed/all'
    | '/feed/create'
    | '/feed/subscribe'
    | '/mypage/following'
    | '/mypage/purchases'
    | '/mypage/settings'
    | '/mypage/subscriptions'
    | '/mypage/tier'
    | '/mypage/version'
    | '/partner/apply'
    | '/partner/dashboard'
    | '/partners/$memberCode'
    | '/partners/$partnerId'
    | '/payment/fail'
    | '/payment/success'
    | '/roulette/$memberCode'
    | '/store/cart'
    | '/store/wishlist'
    | '/stream/live'
    | '/stream/replay'
    | '/stream/voice'
    | '/timesheet/admin'
    | '/admin/'
    | '/partners/'
    | '/stream/'
    | '/timesheet/'
    | '/dashboard/partner/roulette'
    | '/dashboard/partner/roulette-requests'
    | '/mypage/inventory/digital-collection'
    | '/mypage/inventory/roulette'
    | '/mypage/purchases/$orderId'
    | '/mypage/saved/$albumId'
    | '/store/admin/collaboration'
    | '/store/admin/insights'
    | '/store/admin/shipment-requests'
    | '/store/digital/downloads'
    | '/store/orders/$orderId'
    | '/store/partner/agreement'
    | '/store/partner/collaboration'
    | '/store/partner/insights'
    | '/store/partner/orders'
    | '/store/partner/products'
    | '/store/payment/fail'
    | '/store/payment/success'
    | '/store/products/$productId'
    | '/store/refunds/$refundId'
    | '/stream/chat/$roomId'
    | '/stream/video/$roomId'
    | '/timesheet/admin/audit'
    | '/timesheet/admin/managers'
    | '/timesheet/admin/partners'
    | '/timesheet/admin/settings'
    | '/timesheet/admin/stats'
    | '/timesheet/admin/stores'
    | '/mypage/saved/'
    | '/store/orders/'
    | '/store/refunds/'
    | '/timesheet/admin/'
    | '/dashboard/partner/inventory/roulette'
    | '/store/digital/orders/$orderId'
    | '/store/orders/$orderId/viewer'
    | '/store/partner/products/new'
    | '/stream/video/hls-rehearsal/$roomId'
    | '/stream/video/rehearsal/$roomId'
    | '/stream/video/webrtc-broadcast/$roomId'
    | '/store/partner/products/$productId/edit'
    | '/store/partner/products/$productId/preview'
    | '/store/partner/products/$productId/upload'
    | '/store/partner/products/new/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  ChatRoute: typeof ChatRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  LoginTesterRoute: typeof LoginTesterRoute
  MembershipRoute: typeof MembershipRoute
  MessagesRoute: typeof MessagesRoute
  MypageRoute: typeof MypageRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PointsRoute: typeof PointsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardPartnerRoute: typeof DashboardPartnerRouteWithChildren
  DevRouletteRoute: typeof DevRouletteRoute
  FeedPostIdRoute: typeof FeedPostIdRoute
  FeedAllRoute: typeof FeedAllRoute
  FeedCreateRoute: typeof FeedCreateRoute
  FeedSubscribeRoute: typeof FeedSubscribeRoute
  PartnersMemberCodeRoute: typeof PartnersMemberCodeRoute
  PartnersPartnerIdRoute: typeof PartnersPartnerIdRoute
  PaymentFailRoute: typeof PaymentFailRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RouletteMemberCodeRoute: typeof RouletteMemberCodeRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreWishlistRoute: typeof StoreWishlistRoute
  StreamLiveRoute: typeof StreamLiveRoute
  StreamReplayRoute: typeof StreamReplayRoute
  StreamVoiceRoute: typeof StreamVoiceRoute
  TimesheetAdminRoute: typeof TimesheetAdminRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  StreamIndexRoute: typeof StreamIndexRoute
  TimesheetIndexRoute: typeof TimesheetIndexRoute
  StoreAdminCollaborationRoute: typeof StoreAdminCollaborationRoute
  StoreAdminInsightsRoute: typeof StoreAdminInsightsRoute
  StoreAdminShipmentRequestsRoute: typeof StoreAdminShipmentRequestsRoute
  StoreDigitalDownloadsRoute: typeof StoreDigitalDownloadsRoute
  StoreOrdersOrderIdRoute: typeof StoreOrdersOrderIdRouteWithChildren
  StorePartnerAgreementRoute: typeof StorePartnerAgreementRoute
  StorePartnerCollaborationRoute: typeof StorePartnerCollaborationRoute
  StorePartnerInsightsRoute: typeof StorePartnerInsightsRoute
  StorePartnerOrdersRoute: typeof StorePartnerOrdersRoute
  StorePartnerProductsRoute: typeof StorePartnerProductsRouteWithChildren
  StorePaymentFailRoute: typeof StorePaymentFailRoute
  StorePaymentSuccessRoute: typeof StorePaymentSuccessRoute
  StoreProductsProductIdRoute: typeof StoreProductsProductIdRoute
  StoreRefundsRefundIdRoute: typeof StoreRefundsRefundIdRoute
  StreamChatRoomIdRoute: typeof StreamChatRoomIdRoute
  StreamVideoRoomIdRoute: typeof StreamVideoRoomIdRoute
  StoreOrdersIndexRoute: typeof StoreOrdersIndexRoute
  StoreRefundsIndexRoute: typeof StoreRefundsIndexRoute
  StoreDigitalOrdersOrderIdRoute: typeof StoreDigitalOrdersOrderIdRoute
  StreamVideoHlsRehearsalRoomIdRoute: typeof StreamVideoHlsRehearsalRoomIdRoute
  StreamVideoRehearsalRoomIdRoute: typeof StreamVideoRehearsalRoomIdRoute
  StreamVideoWebrtcBroadcastRoomIdRoute: typeof StreamVideoWebrtcBroadcastRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loginTester': {
      id: '/loginTester'
      path: '/loginTester'
      fullPath: '/loginTester'
      preLoaderRoute: typeof LoginTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheet/': {
      id: '/timesheet/'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof TimesheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/': {
      id: '/stream/'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheet/admin': {
      id: '/timesheet/admin'
      path: '/timesheet/admin'
      fullPath: '/timesheet/admin'
      preLoaderRoute: typeof TimesheetAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/voice': {
      id: '/stream/voice'
      path: '/stream/voice'
      fullPath: '/stream/voice'
      preLoaderRoute: typeof StreamVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/replay': {
      id: '/stream/replay'
      path: '/stream/replay'
      fullPath: '/stream/replay'
      preLoaderRoute: typeof StreamReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/live': {
      id: '/stream/live'
      path: '/stream/live'
      fullPath: '/stream/live'
      preLoaderRoute: typeof StreamLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/wishlist': {
      id: '/store/wishlist'
      path: '/store/wishlist'
      fullPath: '/store/wishlist'
      preLoaderRoute: typeof StoreWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/store/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette/$memberCode': {
      id: '/roulette/$memberCode'
      path: '/roulette/$memberCode'
      fullPath: '/roulette/$memberCode'
      preLoaderRoute: typeof RouletteMemberCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/fail': {
      id: '/payment/fail'
      path: '/payment/fail'
      fullPath: '/payment/fail'
      preLoaderRoute: typeof PaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$partnerId': {
      id: '/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PartnersPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$memberCode': {
      id: '/partners/$memberCode'
      path: '/partners/$memberCode'
      fullPath: '/partners/$memberCode'
      preLoaderRoute: typeof PartnersMemberCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/apply': {
      id: '/partner/apply'
      path: '/apply'
      fullPath: '/partner/apply'
      preLoaderRoute: typeof PartnerApplyRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/mypage/version': {
      id: '/mypage/version'
      path: '/version'
      fullPath: '/mypage/version'
      preLoaderRoute: typeof MypageVersionRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/tier': {
      id: '/mypage/tier'
      path: '/tier'
      fullPath: '/mypage/tier'
      preLoaderRoute: typeof MypageTierRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/subscriptions': {
      id: '/mypage/subscriptions'
      path: '/subscriptions'
      fullPath: '/mypage/subscriptions'
      preLoaderRoute: typeof MypageSubscriptionsRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/settings': {
      id: '/mypage/settings'
      path: '/settings'
      fullPath: '/mypage/settings'
      preLoaderRoute: typeof MypageSettingsRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/purchases': {
      id: '/mypage/purchases'
      path: '/purchases'
      fullPath: '/mypage/purchases'
      preLoaderRoute: typeof MypagePurchasesRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/following': {
      id: '/mypage/following'
      path: '/following'
      fullPath: '/mypage/following'
      preLoaderRoute: typeof MypageFollowingRouteImport
      parentRoute: typeof MypageRoute
    }
    '/feed/subscribe': {
      id: '/feed/subscribe'
      path: '/feed/subscribe'
      fullPath: '/feed/subscribe'
      preLoaderRoute: typeof FeedSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/create': {
      id: '/feed/create'
      path: '/feed/create'
      fullPath: '/feed/create'
      preLoaderRoute: typeof FeedCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/all': {
      id: '/feed/all'
      path: '/feed/all'
      fullPath: '/feed/all'
      preLoaderRoute: typeof FeedAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$postId': {
      id: '/feed/$postId'
      path: '/feed/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof FeedPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/roulette': {
      id: '/dev/roulette'
      path: '/dev/roulette'
      fullPath: '/dev/roulette'
      preLoaderRoute: typeof DevRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/partner': {
      id: '/dashboard/partner'
      path: '/dashboard/partner'
      fullPath: '/dashboard/partner'
      preLoaderRoute: typeof DashboardPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof ChatRoute
    }
    '/timesheet/admin/': {
      id: '/timesheet/admin/'
      path: '/'
      fullPath: '/timesheet/admin/'
      preLoaderRoute: typeof TimesheetAdminIndexRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/store/refunds/': {
      id: '/store/refunds/'
      path: '/store/refunds'
      fullPath: '/store/refunds'
      preLoaderRoute: typeof StoreRefundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/orders/': {
      id: '/store/orders/'
      path: '/store/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/saved/': {
      id: '/mypage/saved/'
      path: '/saved'
      fullPath: '/mypage/saved'
      preLoaderRoute: typeof MypageSavedIndexRouteImport
      parentRoute: typeof MypageRoute
    }
    '/timesheet/admin/stores': {
      id: '/timesheet/admin/stores'
      path: '/stores'
      fullPath: '/timesheet/admin/stores'
      preLoaderRoute: typeof TimesheetAdminStoresRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/timesheet/admin/stats': {
      id: '/timesheet/admin/stats'
      path: '/stats'
      fullPath: '/timesheet/admin/stats'
      preLoaderRoute: typeof TimesheetAdminStatsRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/timesheet/admin/settings': {
      id: '/timesheet/admin/settings'
      path: '/settings'
      fullPath: '/timesheet/admin/settings'
      preLoaderRoute: typeof TimesheetAdminSettingsRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/timesheet/admin/partners': {
      id: '/timesheet/admin/partners'
      path: '/partners'
      fullPath: '/timesheet/admin/partners'
      preLoaderRoute: typeof TimesheetAdminPartnersRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/timesheet/admin/managers': {
      id: '/timesheet/admin/managers'
      path: '/managers'
      fullPath: '/timesheet/admin/managers'
      preLoaderRoute: typeof TimesheetAdminManagersRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/timesheet/admin/audit': {
      id: '/timesheet/admin/audit'
      path: '/audit'
      fullPath: '/timesheet/admin/audit'
      preLoaderRoute: typeof TimesheetAdminAuditRouteImport
      parentRoute: typeof TimesheetAdminRoute
    }
    '/stream/video/$roomId': {
      id: '/stream/video/$roomId'
      path: '/stream/video/$roomId'
      fullPath: '/stream/video/$roomId'
      preLoaderRoute: typeof StreamVideoRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/chat/$roomId': {
      id: '/stream/chat/$roomId'
      path: '/stream/chat/$roomId'
      fullPath: '/stream/chat/$roomId'
      preLoaderRoute: typeof StreamChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/refunds/$refundId': {
      id: '/store/refunds/$refundId'
      path: '/store/refunds/$refundId'
      fullPath: '/store/refunds/$refundId'
      preLoaderRoute: typeof StoreRefundsRefundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/products/$productId': {
      id: '/store/products/$productId'
      path: '/store/products/$productId'
      fullPath: '/store/products/$productId'
      preLoaderRoute: typeof StoreProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/payment/success': {
      id: '/store/payment/success'
      path: '/store/payment/success'
      fullPath: '/store/payment/success'
      preLoaderRoute: typeof StorePaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/payment/fail': {
      id: '/store/payment/fail'
      path: '/store/payment/fail'
      fullPath: '/store/payment/fail'
      preLoaderRoute: typeof StorePaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/partner/products': {
      id: '/store/partner/products'
      path: '/store/partner/products'
      fullPath: '/store/partner/products'
      preLoaderRoute: typeof StorePartnerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/partner/orders': {
      id: '/store/partner/orders'
      path: '/store/partner/orders'
      fullPath: '/store/partner/orders'
      preLoaderRoute: typeof StorePartnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/partner/insights': {
      id: '/store/partner/insights'
      path: '/store/partner/insights'
      fullPath: '/store/partner/insights'
      preLoaderRoute: typeof StorePartnerInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/partner/collaboration': {
      id: '/store/partner/collaboration'
      path: '/store/partner/collaboration'
      fullPath: '/store/partner/collaboration'
      preLoaderRoute: typeof StorePartnerCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/partner/agreement': {
      id: '/store/partner/agreement'
      path: '/store/partner/agreement'
      fullPath: '/store/partner/agreement'
      preLoaderRoute: typeof StorePartnerAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/orders/$orderId': {
      id: '/store/orders/$orderId'
      path: '/store/orders/$orderId'
      fullPath: '/store/orders/$orderId'
      preLoaderRoute: typeof StoreOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/digital/downloads': {
      id: '/store/digital/downloads'
      path: '/store/digital/downloads'
      fullPath: '/store/digital/downloads'
      preLoaderRoute: typeof StoreDigitalDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/admin/shipment-requests': {
      id: '/store/admin/shipment-requests'
      path: '/store/admin/shipment-requests'
      fullPath: '/store/admin/shipment-requests'
      preLoaderRoute: typeof StoreAdminShipmentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/admin/insights': {
      id: '/store/admin/insights'
      path: '/store/admin/insights'
      fullPath: '/store/admin/insights'
      preLoaderRoute: typeof StoreAdminInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/admin/collaboration': {
      id: '/store/admin/collaboration'
      path: '/store/admin/collaboration'
      fullPath: '/store/admin/collaboration'
      preLoaderRoute: typeof StoreAdminCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/saved/$albumId': {
      id: '/mypage/saved/$albumId'
      path: '/saved/$albumId'
      fullPath: '/mypage/saved/$albumId'
      preLoaderRoute: typeof MypageSavedAlbumIdRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/purchases/$orderId': {
      id: '/mypage/purchases/$orderId'
      path: '/$orderId'
      fullPath: '/mypage/purchases/$orderId'
      preLoaderRoute: typeof MypagePurchasesOrderIdRouteImport
      parentRoute: typeof MypagePurchasesRoute
    }
    '/mypage/inventory/roulette': {
      id: '/mypage/inventory/roulette'
      path: '/inventory/roulette'
      fullPath: '/mypage/inventory/roulette'
      preLoaderRoute: typeof MypageInventoryRouletteRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/inventory/digital-collection': {
      id: '/mypage/inventory/digital-collection'
      path: '/inventory/digital-collection'
      fullPath: '/mypage/inventory/digital-collection'
      preLoaderRoute: typeof MypageInventoryDigitalCollectionRouteImport
      parentRoute: typeof MypageRoute
    }
    '/dashboard/partner/roulette-requests': {
      id: '/dashboard/partner/roulette-requests'
      path: '/roulette-requests'
      fullPath: '/dashboard/partner/roulette-requests'
      preLoaderRoute: typeof DashboardPartnerRouletteRequestsRouteImport
      parentRoute: typeof DashboardPartnerRoute
    }
    '/dashboard/partner/roulette': {
      id: '/dashboard/partner/roulette'
      path: '/roulette'
      fullPath: '/dashboard/partner/roulette'
      preLoaderRoute: typeof DashboardPartnerRouletteRouteImport
      parentRoute: typeof DashboardPartnerRoute
    }
    '/stream/video/webrtc-broadcast/$roomId': {
      id: '/stream/video/webrtc-broadcast/$roomId'
      path: '/stream/video/webrtc-broadcast/$roomId'
      fullPath: '/stream/video/webrtc-broadcast/$roomId'
      preLoaderRoute: typeof StreamVideoWebrtcBroadcastRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/video/rehearsal/$roomId': {
      id: '/stream/video/rehearsal/$roomId'
      path: '/stream/video/rehearsal/$roomId'
      fullPath: '/stream/video/rehearsal/$roomId'
      preLoaderRoute: typeof StreamVideoRehearsalRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/video/hls-rehearsal/$roomId': {
      id: '/stream/video/hls-rehearsal/$roomId'
      path: '/stream/video/hls-rehearsal/$roomId'
      fullPath: '/stream/video/hls-rehearsal/$roomId'
      preLoaderRoute: typeof StreamVideoHlsRehearsalRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/partner/products/new': {
      id: '/store/partner/products/new'
      path: '/new'
      fullPath: '/store/partner/products/new'
      preLoaderRoute: typeof StorePartnerProductsNewRouteImport
      parentRoute: typeof StorePartnerProductsRoute
    }
    '/store/orders/$orderId/viewer': {
      id: '/store/orders/$orderId/viewer'
      path: '/viewer'
      fullPath: '/store/orders/$orderId/viewer'
      preLoaderRoute: typeof StoreOrdersOrderIdViewerRouteImport
      parentRoute: typeof StoreOrdersOrderIdRoute
    }
    '/store/digital/orders/$orderId': {
      id: '/store/digital/orders/$orderId'
      path: '/store/digital/orders/$orderId'
      fullPath: '/store/digital/orders/$orderId'
      preLoaderRoute: typeof StoreDigitalOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/partner/inventory/roulette': {
      id: '/dashboard/partner/inventory/roulette'
      path: '/inventory/roulette'
      fullPath: '/dashboard/partner/inventory/roulette'
      preLoaderRoute: typeof DashboardPartnerInventoryRouletteRouteImport
      parentRoute: typeof DashboardPartnerRoute
    }
    '/store/partner/products/new/upload': {
      id: '/store/partner/products/new/upload'
      path: '/upload'
      fullPath: '/store/partner/products/new/upload'
      preLoaderRoute: typeof StorePartnerProductsNewUploadRouteImport
      parentRoute: typeof StorePartnerProductsNewRoute
    }
    '/store/partner/products/$productId/upload': {
      id: '/store/partner/products/$productId/upload'
      path: '/$productId/upload'
      fullPath: '/store/partner/products/$productId/upload'
      preLoaderRoute: typeof StorePartnerProductsProductIdUploadRouteImport
      parentRoute: typeof StorePartnerProductsRoute
    }
    '/store/partner/products/$productId/preview': {
      id: '/store/partner/products/$productId/preview'
      path: '/$productId/preview'
      fullPath: '/store/partner/products/$productId/preview'
      preLoaderRoute: typeof StorePartnerProductsProductIdPreviewRouteImport
      parentRoute: typeof StorePartnerProductsRoute
    }
    '/store/partner/products/$productId/edit': {
      id: '/store/partner/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/store/partner/products/$productId/edit'
      preLoaderRoute: typeof StorePartnerProductsProductIdEditRouteImport
      parentRoute: typeof StorePartnerProductsRoute
    }
  }
}

interface ChatRouteChildren {
  ChatNewRoute: typeof ChatNewRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatNewRoute: ChatNewRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface MypagePurchasesRouteChildren {
  MypagePurchasesOrderIdRoute: typeof MypagePurchasesOrderIdRoute
}

const MypagePurchasesRouteChildren: MypagePurchasesRouteChildren = {
  MypagePurchasesOrderIdRoute: MypagePurchasesOrderIdRoute,
}

const MypagePurchasesRouteWithChildren = MypagePurchasesRoute._addFileChildren(
  MypagePurchasesRouteChildren,
)

interface MypageRouteChildren {
  MypageFollowingRoute: typeof MypageFollowingRoute
  MypagePurchasesRoute: typeof MypagePurchasesRouteWithChildren
  MypageSettingsRoute: typeof MypageSettingsRoute
  MypageSubscriptionsRoute: typeof MypageSubscriptionsRoute
  MypageTierRoute: typeof MypageTierRoute
  MypageVersionRoute: typeof MypageVersionRoute
  MypageInventoryDigitalCollectionRoute: typeof MypageInventoryDigitalCollectionRoute
  MypageInventoryRouletteRoute: typeof MypageInventoryRouletteRoute
  MypageSavedAlbumIdRoute: typeof MypageSavedAlbumIdRoute
  MypageSavedIndexRoute: typeof MypageSavedIndexRoute
}

const MypageRouteChildren: MypageRouteChildren = {
  MypageFollowingRoute: MypageFollowingRoute,
  MypagePurchasesRoute: MypagePurchasesRouteWithChildren,
  MypageSettingsRoute: MypageSettingsRoute,
  MypageSubscriptionsRoute: MypageSubscriptionsRoute,
  MypageTierRoute: MypageTierRoute,
  MypageVersionRoute: MypageVersionRoute,
  MypageInventoryDigitalCollectionRoute: MypageInventoryDigitalCollectionRoute,
  MypageInventoryRouletteRoute: MypageInventoryRouletteRoute,
  MypageSavedAlbumIdRoute: MypageSavedAlbumIdRoute,
  MypageSavedIndexRoute: MypageSavedIndexRoute,
}

const MypageRouteWithChildren =
  MypageRoute._addFileChildren(MypageRouteChildren)

interface PartnerRouteChildren {
  PartnerApplyRoute: typeof PartnerApplyRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerApplyRoute: PartnerApplyRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface DashboardPartnerRouteChildren {
  DashboardPartnerRouletteRoute: typeof DashboardPartnerRouletteRoute
  DashboardPartnerRouletteRequestsRoute: typeof DashboardPartnerRouletteRequestsRoute
  DashboardPartnerInventoryRouletteRoute: typeof DashboardPartnerInventoryRouletteRoute
}

const DashboardPartnerRouteChildren: DashboardPartnerRouteChildren = {
  DashboardPartnerRouletteRoute: DashboardPartnerRouletteRoute,
  DashboardPartnerRouletteRequestsRoute: DashboardPartnerRouletteRequestsRoute,
  DashboardPartnerInventoryRouletteRoute:
    DashboardPartnerInventoryRouletteRoute,
}

const DashboardPartnerRouteWithChildren =
  DashboardPartnerRoute._addFileChildren(DashboardPartnerRouteChildren)

interface TimesheetAdminRouteChildren {
  TimesheetAdminAuditRoute: typeof TimesheetAdminAuditRoute
  TimesheetAdminManagersRoute: typeof TimesheetAdminManagersRoute
  TimesheetAdminPartnersRoute: typeof TimesheetAdminPartnersRoute
  TimesheetAdminSettingsRoute: typeof TimesheetAdminSettingsRoute
  TimesheetAdminStatsRoute: typeof TimesheetAdminStatsRoute
  TimesheetAdminStoresRoute: typeof TimesheetAdminStoresRoute
  TimesheetAdminIndexRoute: typeof TimesheetAdminIndexRoute
}

const TimesheetAdminRouteChildren: TimesheetAdminRouteChildren = {
  TimesheetAdminAuditRoute: TimesheetAdminAuditRoute,
  TimesheetAdminManagersRoute: TimesheetAdminManagersRoute,
  TimesheetAdminPartnersRoute: TimesheetAdminPartnersRoute,
  TimesheetAdminSettingsRoute: TimesheetAdminSettingsRoute,
  TimesheetAdminStatsRoute: TimesheetAdminStatsRoute,
  TimesheetAdminStoresRoute: TimesheetAdminStoresRoute,
  TimesheetAdminIndexRoute: TimesheetAdminIndexRoute,
}

const TimesheetAdminRouteWithChildren = TimesheetAdminRoute._addFileChildren(
  TimesheetAdminRouteChildren,
)

interface StoreOrdersOrderIdRouteChildren {
  StoreOrdersOrderIdViewerRoute: typeof StoreOrdersOrderIdViewerRoute
}

const StoreOrdersOrderIdRouteChildren: StoreOrdersOrderIdRouteChildren = {
  StoreOrdersOrderIdViewerRoute: StoreOrdersOrderIdViewerRoute,
}

const StoreOrdersOrderIdRouteWithChildren =
  StoreOrdersOrderIdRoute._addFileChildren(StoreOrdersOrderIdRouteChildren)

interface StorePartnerProductsNewRouteChildren {
  StorePartnerProductsNewUploadRoute: typeof StorePartnerProductsNewUploadRoute
}

const StorePartnerProductsNewRouteChildren: StorePartnerProductsNewRouteChildren =
  {
    StorePartnerProductsNewUploadRoute: StorePartnerProductsNewUploadRoute,
  }

const StorePartnerProductsNewRouteWithChildren =
  StorePartnerProductsNewRoute._addFileChildren(
    StorePartnerProductsNewRouteChildren,
  )

interface StorePartnerProductsRouteChildren {
  StorePartnerProductsNewRoute: typeof StorePartnerProductsNewRouteWithChildren
  StorePartnerProductsProductIdEditRoute: typeof StorePartnerProductsProductIdEditRoute
  StorePartnerProductsProductIdPreviewRoute: typeof StorePartnerProductsProductIdPreviewRoute
  StorePartnerProductsProductIdUploadRoute: typeof StorePartnerProductsProductIdUploadRoute
}

const StorePartnerProductsRouteChildren: StorePartnerProductsRouteChildren = {
  StorePartnerProductsNewRoute: StorePartnerProductsNewRouteWithChildren,
  StorePartnerProductsProductIdEditRoute:
    StorePartnerProductsProductIdEditRoute,
  StorePartnerProductsProductIdPreviewRoute:
    StorePartnerProductsProductIdPreviewRoute,
  StorePartnerProductsProductIdUploadRoute:
    StorePartnerProductsProductIdUploadRoute,
}

const StorePartnerProductsRouteWithChildren =
  StorePartnerProductsRoute._addFileChildren(StorePartnerProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  ChatRoute: ChatRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  LoginTesterRoute: LoginTesterRoute,
  MembershipRoute: MembershipRoute,
  MessagesRoute: MessagesRoute,
  MypageRoute: MypageRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PointsRoute: PointsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardPartnerRoute: DashboardPartnerRouteWithChildren,
  DevRouletteRoute: DevRouletteRoute,
  FeedPostIdRoute: FeedPostIdRoute,
  FeedAllRoute: FeedAllRoute,
  FeedCreateRoute: FeedCreateRoute,
  FeedSubscribeRoute: FeedSubscribeRoute,
  PartnersMemberCodeRoute: PartnersMemberCodeRoute,
  PartnersPartnerIdRoute: PartnersPartnerIdRoute,
  PaymentFailRoute: PaymentFailRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RouletteMemberCodeRoute: RouletteMemberCodeRoute,
  StoreCartRoute: StoreCartRoute,
  StoreWishlistRoute: StoreWishlistRoute,
  StreamLiveRoute: StreamLiveRoute,
  StreamReplayRoute: StreamReplayRoute,
  StreamVoiceRoute: StreamVoiceRoute,
  TimesheetAdminRoute: TimesheetAdminRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  StreamIndexRoute: StreamIndexRoute,
  TimesheetIndexRoute: TimesheetIndexRoute,
  StoreAdminCollaborationRoute: StoreAdminCollaborationRoute,
  StoreAdminInsightsRoute: StoreAdminInsightsRoute,
  StoreAdminShipmentRequestsRoute: StoreAdminShipmentRequestsRoute,
  StoreDigitalDownloadsRoute: StoreDigitalDownloadsRoute,
  StoreOrdersOrderIdRoute: StoreOrdersOrderIdRouteWithChildren,
  StorePartnerAgreementRoute: StorePartnerAgreementRoute,
  StorePartnerCollaborationRoute: StorePartnerCollaborationRoute,
  StorePartnerInsightsRoute: StorePartnerInsightsRoute,
  StorePartnerOrdersRoute: StorePartnerOrdersRoute,
  StorePartnerProductsRoute: StorePartnerProductsRouteWithChildren,
  StorePaymentFailRoute: StorePaymentFailRoute,
  StorePaymentSuccessRoute: StorePaymentSuccessRoute,
  StoreProductsProductIdRoute: StoreProductsProductIdRoute,
  StoreRefundsRefundIdRoute: StoreRefundsRefundIdRoute,
  StreamChatRoomIdRoute: StreamChatRoomIdRoute,
  StreamVideoRoomIdRoute: StreamVideoRoomIdRoute,
  StoreOrdersIndexRoute: StoreOrdersIndexRoute,
  StoreRefundsIndexRoute: StoreRefundsIndexRoute,
  StoreDigitalOrdersOrderIdRoute: StoreDigitalOrdersOrderIdRoute,
  StreamVideoHlsRehearsalRoomIdRoute: StreamVideoHlsRehearsalRoomIdRoute,
  StreamVideoRehearsalRoomIdRoute: StreamVideoRehearsalRoomIdRoute,
  StreamVideoWebrtcBroadcastRoomIdRoute: StreamVideoWebrtcBroadcastRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
